# Creating Arrays with Numpy
There are many times when you might need to create some data to aid some analysis or do some idealized calculations. We'll cover a few of the most relevant array creation methods and a few more mathematical functions.

In [ ]:
import numpy as np

## 1D Arrays
There are two useful methods for creating 1D arrays that can be filled with sequential numbers.
* `np.arange`
   - This function is similar to the native Python `range()` function in that it creates a sequential set of values from the starting value to one less than the stopping value, by the step amount. The difference is that we get a Numpy array back instead of just an iterable object. Additionally, this function can give either integers or floating values in return. To get floating values, simply make at least one of the values (e.g., start, stop, step) as a floating point number.

```python
a = np.arange(1, 11, 1)
print(a)
```
Output:
```
[1 2 3 4 5 6 7 8 9 10]
```

* `np.linspace`
   - This function creates a sequential set of numbers, but instead of specifying a step value, you can specify how many points you want between the starting and ending points, inclusive of the end point values. Note: Here we are inclusive of the starting and ending points.
   
```python
b = np.linspace(-5, 5, 10)
print(b)
```
Output:
```
[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]
```

In [ ]:
# arange function


In [ ]:
# linspace function


## Uniform Arrays (multidimensional)
* `np.zeros` and `np.zeros_like`
   - This function will create an array filled with zeros given a certain shape (e.g., (3, 2)). Can set the dtype to be float64 or int64. The `zeros_like` function takes as input another array and will use its shape to create a new array that is the same shape, but filled with zeros.
* `np.ones` and `np.ones_like`
   - The same as the `zeros` and `zeros_like` function except that the array is filled with ones.
   
These types of array creation can be useful for performing calculations, or to fill in as you process some data.

To assign new values to a part of an array, you only need to use the index address to set the value. For example,
```python
new_array = np.zeros((3, 4))

# Assign a single value
new_array[2, 3] = 5
print(new_array)
print()

# Assign a value to a column
new_array[:, 2] = 42
print(new_array)
```
Output:
```
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 5.]]

[[ 0.  0. 42.  0.]
 [ 0.  0. 42.  0.]
 [ 0.  0. 42.  5.]]
```

## Merging Two 1D Arrays into 2D Arrays
* `np.meshgrid`
   - Sometimes you have two 1D arrays that represent some coordinate values, such as latitude and longitude points, that we want to make into a 2D grid for analysis or plotting purposes. The `meshgrid` function takes two 1D arrays and generates two 2D arrays.

```python
x = np.arange(-5, 5)
y = np.arange(0, 8)
xx, yy = np.meshgrid(x, y)
print(xx)
print()
print(yy)
```
Output:
```
[[-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]]
 
 [[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]]
```

You can think of the x-values as longitudes, staying the same within a single column and the y-values as latitudes where they stay the same across a row.

In [ ]:
# Lon/Lat Example


## Random Number Arrays
There are any number of times when you might want/need to generate random values for choosing a sample of your data, or generating some synthetic data with the bounds of some fixed values. Other times you might want to have random values that you'll be able to compare to another set of data to determine if the populations are statistically different.

* `np.random.randint`
   - This function generates random integers over a low (inclusive) to high (exclusive) value. If only one value is given, then it will act as a high value and use a defualt low value of zero.
* `np.random.rand`
   - This function will take a shape as input and output an array of random value in the range of `[0, 1)` in the shape that was specified.
* `np.random.randn`
   - This function will take a shape as input and output an array of values from the standard normal distribution in the shape that was specified.
* `np.random.random_sample`
   - This function will take a size value (e.g., 5) or shape and output a float array of the specified size in the open range of `[0, 1)`.

```python
# Random Sample for generating values over a specified range
north_lat = 50.0
south_lat = 22.5
random_lats = (north_lat - south_lat) * np.random.random_sample(5) + south_lat
print(random_lats)
```
Output:
```
[31.04480726 40.90859657 35.90784107 31.7846562  42.29942737]
```

* `np.random.normal`
   - This function will take a mean, standard deviation, and size/shape parameter to output a random sample from a Gaussian distribution based on the input mean and standard deviation for the size of the array given.

In [ ]:
# Random Ints for subset lat array for five values


In [ ]:
# Generate a Random Sample of 10 temperatures within the range of -10 to 90


## Other Numpy Functions
There are many other mathematical functions that are available in Numpy and its closely related cousin, SciPy.  That work well for vectorized computation.

Numpy Mathematical Functions: https://numpy.org/doc/stable/reference/routines.math.html

Scipy Documentation: https://docs.scipy.org/doc/scipy-1.7.0/reference/

Some common mathematical functions
* `np.exp`
* `np.sin`
* `np.cos`
* `np.tan`
* `np.deg2rad`
* `np.rad2deg`

Some common constant values (https://numpy.org/doc/stable/reference/constants.html)
* `np.pi`
* `np.e`


## Exercise 1
Create an array of equaly spaced points of degree values from zero to 360 with a total of 100 points. Convert the degree values to radian values and store in their own variable namespace. Use the computed radian values to then calculate the values of sine and cosine and store in separate variables. Print the original degree array, the computed radian array and the sine and cosine arrays to the screen.