## Lists vs. Tuple

Python doesn't have a true array object. The closest thing to an array is a Python List (which are sometimes called array-like objects). Many of their properties are the same, but there are some notable differences depending on what you are trying to do. There are two ways to define a list, 1) using square brackets or 2) using the list function `list()`. For example the following two are equivalent,

```python
a = [1,2,3,4,5]

a = list(1,2,3,4,5)
```

Lists are mutable objects, meaning that you can redefine individual elements.

Another array-like object in Python is the Tuple. Tuples are different than lists in that they are immutable objects, meaning they can't be changed once assigned. Tuples can also be defined in two different ways, 1) using parentheses or 2) using the tuple function `tuple()`. For example, the following two tuple assignments are equivalent,

```python
b = (10,20,30,40,50)

b = tuple(10,20,30,40,50)
```

In [1]:
# A list
a = [0,1,2,3,4,5,6,7,8,9]
print("Printing a list")
print(a)

Printing a list
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [2]:
# Try a reassignment of a tuple object
a[5] = 500
print(a)

[0, 1, 2, 3, 4, 500, 6, 7, 8, 9]


In [3]:
# A tuple
b = (10,11,12,13,'Kevin',15,16,17,18,19)
print("Printing a tuple")
print(b)

Printing a tuple
(10, 11, 12, 13, 'Kevin', 15, 16, 17, 18, 19)


In [4]:
# Try a reassignment of a tuple object
b[5] = 'Goebbert'

TypeError: 'tuple' object does not support item assignment

Both lists and tuples can contain different data types in the same variable. This can be adventageous at times.

In [5]:
a[5] = 'Kevin'
print(a)

[0, 1, 2, 3, 4, 'Kevin', 6, 7, 8, 9]


## List and Tuple Methods

### List Object
There are a number of methods that are available for list objects including: ```append(), copy(), count(), index()```.

### Tuple Object
There are only two methods available for the tuple object: ```count(), index()```

In [6]:
a.append('Goebbert')
print(a)

[0, 1, 2, 3, 4, 'Kevin', 6, 7, 8, 9, 'Goebbert']


In [7]:
print(b.index('Kevin'))

4


### Beware of Math with Lists and Tuples

Math works VERY differently! A multiplication creates that number of copies within the list or tuple.

In [8]:
print(a*2)
print(b*2)

[0, 1, 2, 3, 4, 'Kevin', 6, 7, 8, 9, 'Goebbert', 0, 1, 2, 3, 4, 'Kevin', 6, 7, 8, 9, 'Goebbert']
(10, 11, 12, 13, 'Kevin', 15, 16, 17, 18, 19, 10, 11, 12, 13, 'Kevin', 15, 16, 17, 18, 19)


## Multi-dimensional Lists and Tuples

2D Lists are accessed in an odd way - not exactly like a normal 2D array.

In [9]:
list2D = [[1,2,3,4,5],[6,7,8,9,10]]
print(list2D)
print(list2D[1][0])

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
6


## Numpy Arrays

True arrays are available in the NumPy module. This is built on the C programming language and is built to have "fast" array operations. You've already been introduced to this module, but there is a simple method that will take a list and make it into a numpy array, from which you'll have normal array behavior. Just beware that NumPy will require that your array all have the same data type.

In [10]:
import numpy as np

a_array = np.array(list2D)
print(a_array)
print(a_array[0,3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
4


In [11]:
print(list2D*2)
print(a_array*5)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
[[ 5 10 15 20 25]
 [30 35 40 45 50]]


## Dictionaries

Python has the ability to create a mappable data structure, which is called a dictionary. The main way you'll encounter them is through many different data read methods. For example, you saw one with the ```get_upperair_data()``` read function from MetPy. The great thing about a dictionary is that you are able to reference data with a string (or name) as opposed to just an index value. This is very powerful for keeping track of a number of different arrays within a "dataset".

A dictionary is defined in one of two ways, 1) with curly brackets or 2) the ```dict()``` function.

In [12]:
# The following two dictionaries are equivalent
hours = list(range(24))
data1 = {'times':hours,'stn':['VPZ','GYY','ORD','MDW','RFD']}
data2 = dict(times=hours,stn=['VPZ','GYY','ORD','MDW','RFD'])
print(data1)
print(data1==data2)

{'times': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23], 'stn': ['VPZ', 'GYY', 'ORD', 'MDW', 'RFD']}
True


In [13]:
print(data1['stn'])

['VPZ', 'GYY', 'ORD', 'MDW', 'RFD']
